### ISSUE TITLE
Moving asdf-python here

### ISSUE THREAD

**Issue by matan129** [asdf-community/.github#30]
Hi folks, there's the widely-used [asdf-python](https://github.com/danhper/asdf-python) plugin which seems abandoned for a year or so - no new commits, and the maintainer doesn't respond to PRs or issues. The plugin works fine, though - it's a thin wrapper around [python-build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build) which is well maintained and used by PyEnv.

See https://github.com/danhper/asdf-python/issues/116

Python is a very popular language, and making it a first-class citizen of asdf makes a lot of sense. 

So, I suggest forking that plugin to this org (or I can move my own fork, which a patch applied..).

**Comment by bcdady** [comment]
Looks like @danhper responded in the thread (I presume @ tagging him helped).

[asdf-python issue #116](https://github.com/danhper/asdf-python/issues/116#issuecomment-1196052957)

Daniel: See [this section of the README](https://github.com/asdf-community/.github#how-do-i-move-plugins-here) for more info, and please just ask if there's anything any of us can do to support you or otherwise contribute to this effort. Thanks!

**Comment by danhper** [comment]
Hey! I'll try to do it some time this week!
And tagging does help, thanks 😃

**Comment by smorimoto** [comment]
I just added the asdf-python team: https://github.com/asdf-community/infrastructure/commit/dfdb53cf8f28d9ace46633e4a5c2ce4cbc5fa156

**Comment by smorimoto** [comment]
All set!
